### ISSUE TITLE
Auto-Inject

### ISSUE THREAD

**Issue by koocgum** [Novaline-Development/Suggestions#9]
**Please enter your suggestion below.**
Have a toggle-able option for novaline to automatically inject into your game once you get in one.
**Why do you want this added?**
Saves the little effort of clicking a button. Plus, there's no reason as to why it wouldn't be a good option.

**Comment by NovalineDev** [comment]
already exists, it's called AutoAttach in the settings but Novaline is patched right now. I'll make an announcement once it gets unpatched.
